Repository SSU-OpenSource/Front-AOS, pull requests merged in 2023-12, with the labels that each got.

#76 [feat] SH에 유저 이름,닉네임,학번,학과 저장 내용 추가
  app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt
Labels: 예린🌝, PR, feat

#78 [fix/#77] SH에 유저정보 저장안되는 문제 해결
  app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/SignInActivity.kt
Labels: 예린🌝, PR, fix

#81 [feat/#80] 마이페이지 api 작업 및 정보 불러오기, 로그아웃
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangeNicknameActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangePasswordActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/MyInfoFragment.kt
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/fragment_my_info.xml
Labels: 효림🌞, PR, feat

#85 [feat/#84] 마이페이지 API 작업 및 세부 기능 구현
  app/src/main/java/com/ssu/bilda/data/common/ScoreItem.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/MyPageResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/MyPageService.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_rcv_profile_recieved_evaluation.xml
Labels: 효림🌞, PR, feat

#87 [feat] 평가페이지 구현 - 평과 결과 전송 및 과목 불러오기 구현
  app/src/main/java/com/ssu/bilda/data/common/Scores.kt
  app/src/main/java/com/ssu/bilda/data/common/SubjectWithTeamStatus.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/EvaluationRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/SubjectResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/EvaluationService.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/SubjectAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateNameAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/fragment_subject_status.xml
  app/src/main/res/layout/item_rcv_evaluation_subject.xml
  app/src/main/res/layout/item_rcv_evaluation_teammate_name.xml
Labels: 효림🌞, PR, feat, ui

#88 [feat/#86] 평가 페이지 API 작업 및 세부 기능 구현
  app/src/main/java/com/ssu/bilda/data/common/EvaluationTeam.kt
  app/src/main/java/com/ssu/bilda/data/common/EvaluationTeamMember.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/EvaluationTeamResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/EvaluationService.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/SubjectAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateNameAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/fragment_subject_status.xml
  app/src/main/res/layout/item_rcv_evaluation_subject.xml
Labels: 효림🌞, PR, feat

#95 [feat] 과목추가, 유저가속한 과목, 과목 선택시 hasTeam에 따른 분기 완료
  app/src/main/java/com/ssu/bilda/presentation/adapter/UserSubjectAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_team_build_overview.xml
  app/src/main/res/layout/fragment_team_details_by_subject.xml
Labels: 예린🌝, PR, feat

#99 [feat] 챗봇 붙임
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/data/remote/request/GptCompletionChatRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/GptCompletionChatResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/ChatService.kt
  app/src/main/java/com/ssu/bilda/presentation/home/ChatBotActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/bg_chat.xml
  app/src/main/res/layout/activity_chat_bot.xml
Labels: 예린🌝, PR, feat

#102 [feat] 글 조회~ 프로필 조회 (요청 보내기, 수락, 거절) 구현
  app/src/main/java/com/ssu/bilda/data/common/TeamDetail.kt
  app/src/main/java/com/ssu/bilda/data/common/TeamMember.kt
  app/src/main/java/com/ssu/bilda/data/common/TeamMemberWithNickName.kt
  app/src/main/java/com/ssu/bilda/data/common/UserData.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/CreateTeamRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/TeamJoinRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/JoinRequestResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/MyPageReferResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/RejectJoinRequestResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/TeamInfoResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/TeamJoinResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/TeamAcceptRequestService.kt
  app/src/main/java/com/ssu/bilda/data/service/TeamJoinRequestService.kt
  app/src/main/java/com/ssu/bilda/data/service/TeamRejectRequestService.kt
  app/src/main/java/com/ssu/bilda/data/service/TeamService.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateProfileAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/AcceptJoinRequestFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/ProfileReferFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewGeneral.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildWritingFragment.kt
  app/src/main/res/drawable/item_request_gray_box.xml
  app/src/main/res/layout/fragment_accept_join_request.xml
  app/src/main/res/layout/fragment_team_build_post_view_general.xml
  app/src/main/res/layout/fragment_team_build_post_view_leader.xml
  app/src/main/res/layout/item_rcv_request.xml
  app/src/main/res/layout/item_rcv_teammate_profile.xml
Labels: 효림🌞, PR, feat

#103 [feat] 홈 화면 과목 리싸이클러뷰 구현
  app/src/main/java/com/ssu/bilda/presentation/adapter/UserSubjectAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/item_rcv_home.xml
  app/src/main/res/layout/item_rcv_teambuild_name.xml
Labels: 효림🌞, 예린🌝, PR, fix, feat

#104 [fix] 오류 수정
  app/src/main/java/com/ssu/bilda/data/common/UserData.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
  app/src/main/res/layout/fragment_my_info.xml
Labels: 효림🌞, fix

#106 [fix] 홈 팀원 리싸이클러뷰
  app/src/main/java/com/ssu/bilda/presentation/adapter/HomeTeamMemberAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
  app/src/main/res/layout/fragment_team_build_overview.xml
  app/src/main/res/layout/fragment_team_details_by_subject.xml
  app/src/main/res/layout/item_rcv_home_team_members.xml
Labels: 효림🌞, PR, fix

#108 [feat] 평가항목 hasevaluated 에 따른 분기처리
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
Labels: 예린🌝, PR, feat

#109 Feat/teambuilding
  app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateNameAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
Labels: 효림🌞, PR, fix

#111 [fix] 홈화면 분기처리 수정
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
Labels: 예린🌝, PR, fix

#115 [feat] 팀플종료api 및 서브젝트코드관련
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: 예린🌝, PR, feat

#116 [feat] 팀 생성 subjectId 받아오기 구현
  app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildWritingFragment.kt
Labels: 효림🌞, PR, fix

#117 [feat] 모집중 관련 리싸이클러뷰 수정 및 분기처리
  app/src/main/java/com/ssu/bilda/data/remote/response/ResponseDtoListTeamsOfSubjectTDTO.kt
  app/src/main/java/com/ssu/bilda/presentation/adapter/TeamsAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
  app/src/main/res/layout/item_rcv_teambuild_name.xml
Labels: 예린🌝, PR, fix, feat

#122 [feat] 과목이름 넘기기 및 화면 전환 기타 등등 ,,
  app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_team_details_by_subject.xml
Labels: 예린🌝, PR, feat

#123 [fix] 요청 확인 페이지 연결 성공
  app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
Labels: 효림🌞, PR, fix

#124 [fix] 요청 받기 페이지 오류 수정
  app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
Labels: 효림🌞, PR, fix

#125 [fix/#102] 평가페이지 종료된 과목만 불러오기
  app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
  app/src/main/res/layout/fragment_subject_status.xml
Labels: 효림🌞, PR, fix
