Repository SSU-OpenSource/Front-AOS, pull requests merged in 2023-11, with the labels that each got.

#4 [add/#3] 폰트 파일 추가
  app/src/main/res/font/giantsinline.ttf
  app/src/main/res/font/suitebold.ttf
  app/src/main/res/font/suiteextrabold.ttf
  app/src/main/res/font/suiteheavy.ttf
  app/src/main/res/font/suitelight.ttf
  app/src/main/res/font/suitemedium.ttf
  app/src/main/res/font/suiteregular.ttf
  app/src/main/res/font/suitesemibold.ttf
  app/src/main/res/font/yeongdo.ttf
Labels: 예린🌝, PR, add

#7 [ui/#2] 스플래시-회원가입(이메일) 뷰 작업
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/EmailInputActivity.kt
  app/src/main/java/com/ssu/bilda/SplashActivity.kt
  app/src/main/java/com/ssu/bilda/TermsActivity.kt
  app/src/main/res/drawable/bilda_logo.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_blue_btn.xml
  app/src/main/res/drawable/ic_sblue_btn.xml
  app/src/main/res/layout/activity_email_input.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_terms.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 예린🌝, PR, add, ui

#8 [ui/#5] 회원가입(비밀번호)-로그인 화면 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/MyInfoInputActivity.kt
  app/src/main/java/com/ssu/bilda/PwInputActivity.kt
  app/src/main/java/com/ssu/bilda/SignInActivity.kt
  app/src/main/res/layout/activity_email_input.xml
  app/src/main/res/layout/activity_my_info_input.xml
  app/src/main/res/layout/activity_pw_input.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/spinner_major_set.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/spinner_major_items.xml
  app/src/main/res/values/strings.xml
Labels: 예린🌝, PR, add, ui

#11 [ui/#10] bnv 완성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/BnvActivity.kt
  app/src/main/res/drawable/bnv_selector_color.xml
  app/src/main/res/drawable/ic_bnv_home.xml
  app/src/main/res/drawable/ic_bnv_person.xml
  app/src/main/res/drawable/ic_bnv_team.xml
  app/src/main/res/drawable/shape_gray_line_rect.xml
  app/src/main/res/layout/activity_bnv.xml
  app/src/main/res/menu/menu_bnv.xml
Labels: 예린🌝, PR, add, ui

#14 [ui/#9] 홈 화면 뷰 작업
  app/build.gradle.kts
  app/src/main/java/com/ssu/bilda/HomeFragment.kt
  app/src/main/res/drawable/bg_home_subject.xml
  app/src/main/res/drawable/ic_beige_circle.xml
  app/src/main/res/drawable/ic_fab_main.xml
  app/src/main/res/drawable/ic_fab_subject.xml
  app/src/main/res/drawable/ic_fire.xml
  app/src/main/res/drawable/ic_flag.xml
  app/src/main/res/drawable/ic_ssblue_circle.xml
  app/src/main/res/drawable/img_ss_chatbot.png
  app/src/main/res/drawable/img_ss_home.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_rcv_home.xml
  app/src/main/res/values/strings.xml
Labels: 예린🌝, PR, add, ui

#15 [ui/#13] 홈 (과목 추가) 화면 완성
  app/src/main/java/com/ssu/bilda/AddSubjectFragment.kt
  app/src/main/res/drawable/bg_home_scroll.xml
  app/src/main/res/layout/fragment_add_subject.xml
  app/src/main/res/layout/item_rcv_home_add_subject.xml
  app/src/main/res/values/colors.xml
Labels: 예린🌝, PR, add, ui

#17 [ui/#16] 과목별 팀 상세보기 화면 완성
  app/src/main/java/com/ssu/bilda/TeamDetailsBySubjectFragment.kt
  app/src/main/res/drawable/bg_home_team_members.xml
  app/src/main/res/drawable/ic_leader_crown.png
  app/src/main/res/layout/fragment_team_details_by_subject.xml
  app/src/main/res/layout/item_rcv_home_team_members.xml
Labels: 예린🌝, PR, add, ui

#23 [ui/#18] 팀 빌딩 모집중,모집완료 화면 완성
  app/src/main/java/com/ssu/bilda/TeamBuildOverviewFragment.kt
  app/src/main/res/drawable/bg_teambuild_name.xml
  app/src/main/res/drawable/bg_teambuild_status_btn.xml
  app/src/main/res/drawable/img_ss_teambuild.png
  app/src/main/res/drawable/toggle_selector_color.xml
  app/src/main/res/layout/fragment_team_build_overview.xml
  app/src/main/res/layout/item_teambuild_name.xml
Labels: 예린🌝, PR, add, ui

#24 [ui/#6] 이메일인증 다이얼로그 작업 완료
  app/src/main/res/drawable/bg_dialog_btn.xml
  app/src/main/res/drawable/bg_dialog_email.xml
  app/src/main/res/layout/dialog_email.xml
Labels: 예린🌝, PR, add, ui

#29 UI/evaluation
  app/build.gradle.kts
  app/src/main/java/com/ssu/bilda/ProjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/SubjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/TeammateEvalutionFragment.kt
  app/src/main/res/drawable/ic_black_left_arrow_btn.xml
  app/src/main/res/drawable/ic_blue_circle.xml
  app/src/main/res/drawable/ic_blue_evaluation_btn.xml
  app/src/main/res/drawable/ic_blue_save_btn.xml
  app/src/main/res/drawable/ic_blue_teammate_name_btn.xml
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/ic_gray_btn.xml
  app/src/main/res/drawable/ic_gray_right_arrow.xml
  app/src/main/res/drawable/ic_gray_teammate_name_btn.xml
  app/src/main/res/drawable/ic_line_bar.xml
  app/src/main/res/drawable/ic_ss_sunglasses.png
  app/src/main/res/drawable/ic_vertical_line_bar.xml
  app/src/main/res/layout/activity_my_info_input.xml
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/fragment_subject_status.xml
  app/src/main/res/layout/fragment_teammate_evalution.xml
  app/src/main/res/layout/rv_subject_list.xml
  build.gradle.kts
  settings.gradle.kts
Labels: 효림🌞, PR, add, ui

#30 UI/mypage
  app/build.gradle.kts
  app/src/main/java/com/ssu/bilda/MyInfoFragment.kt
  app/src/main/java/com/ssu/bilda/ProfileFragment.kt
  app/src/main/java/com/ssu/bilda/ResetPasswordFragment.kt
  app/src/main/res/drawable/ic_blue_major_name_btn.xml
  app/src/main/res/drawable/ic_blue_profile_major_btn.xml
  app/src/main/res/drawable/ic_blue_profile_my_score_btn.xml
  app/src/main/res/drawable/ic_find_password_email_input_gray_btn.xml
  app/src/main/res/drawable/ic_gray_line.xml
  app/src/main/res/drawable/ic_my_info_change_btn.xml
  app/src/main/res/drawable/ic_profile_evaluation_comment_gray_btn.xml
  app/src/main/res/drawable/ic_profile_gray_subject_btn.xml
  app/src/main/res/drawable/ic_profile_people.xml
  app/src/main/res/drawable/ic_setting_btn.xml
  app/src/main/res/drawable/ic_wgray_next_btn.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_reset_password.xml
  app/src/main/res/layout/item_rcv_evalution_subject.xml
  app/src/main/res/layout/item_rcv_profile_recieved_evaluation.xml
  app/src/main/res/layout/item_rcv_profile_semester_subject.xml
  settings.gradle.kts
Labels: 효림🌞, PR, add, ui

#33 [feat/#25] 회원가입 관련 기능 구현
  .idea/deploymentTargetDropDown.xml
  .idea/ktlint.xml
  app/build.gradle.kts
  app/src/main/java/com/ssu/bilda/EmailInputActivity.kt
  app/src/main/java/com/ssu/bilda/MyInfoInputActivity.kt
  app/src/main/java/com/ssu/bilda/PwInputActivity.kt
  app/src/main/java/com/ssu/bilda/TermsActivity.kt
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/layout/activity_my_info_input.xml
  app/src/main/res/layout/activity_pw_input.xml
  app/src/main/res/layout/dialog_email.xml
  app/src/main/res/values/spinner_major_items.xml
Labels: 예린🌝, PR, feat

#36 [feat/#34] 바텀네비 기능 구현
  app/src/main/java/com/ssu/bilda/BnvActivity.kt
  app/src/main/java/com/ssu/bilda/SignInActivity.kt
  app/src/main/res/layout/activity_bnv.xml
  app/src/main/res/layout/activity_terms_of_privacy.xml
  app/src/main/res/layout/activity_terms_of_use.xml
Labels: 예린🌝, PR, feat

#38 [feat/#35] 약관 페이지 관련 기능 구현
  app/src/main/java/com/ssu/bilda/TermsActivity.kt
  app/src/main/java/com/ssu/bilda/TermsOfPrivacyActivity.kt
  app/src/main/java/com/ssu/bilda/TermsOfUseActivity.kt
Labels: 예린🌝, PR, feat

#51 [ui/#49] 마이페이지 뷰 변경 부분 디자인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangeNicknameActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangePasswordActivity.kt
  app/src/main/res/drawable/ic_blue_next_btn.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_change_password.xml
Labels: 효림🌞, PR, add, ui

#54 [feat/#50] 마이페이지 변경 부분 기능 구현
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangeNicknameActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/ChangePasswordActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/MyInfoFragment.kt
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 효림🌞, PR, fix, feat

#55 [feat/#53] 평가 페이지 뒤로가기 구현
  app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/fragment_subject_status.xml
  app/src/main/res/layout/fragment_teammate_evalution.xml
  build.gradle.kts
Labels: 효림🌞, PR, fix

#57 [ui/#56] 팀 빌딩 페이지 디자인 변경
  app/src/main/res/layout/fragment_profile_refer.xml
  app/src/main/res/layout/fragment_team_build_post_view_general.xml
  app/src/main/res/layout/fragment_team_build_post_view_leader.xml
  app/src/main/res/layout/item_rcv_teammate_profile.xml
Labels: 효림🌞, PR, ui

#58 Setting/retrofit
  app/build.gradle.kts
  app/src/main/java/com/ssu/bilda/data/enums/Department.kt
  app/src/main/java/com/ssu/bilda/data/remote/App.kt
  app/src/main/java/com/ssu/bilda/data/remote/BaseResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/RetrofitImpl.kt
  app/src/main/java/com/ssu/bilda/data/remote/TokenSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/SignUpRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/AuthorizedResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/SignUpResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/EmailService.kt
  app/src/main/java/com/ssu/bilda/data/service/UserService.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/EmailInputActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/TermsActivity.kt
  build.gradle.kts
Labels: 예린🌝, PR, feat

#61 [feat/#60] 팀 빌딩 페이지 다이얼로그 / 스피너 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/data/remote/App.kt
  app/src/main/java/com/ssu/bilda/data/remote/RetrofitImpl.kt
  app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/BaseResponse.kt
  app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/MyInfoFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/SignInActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildWritingFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_project_status.xml
  app/src/main/res/layout/fragment_team_build_writing.xml
Labels: 효림🌞, PR, feat

#66 [feat/#62] 프로필 평가 결과 차트 구현
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
  app/src/main/java/com/ssu/bilda/presentation/mypage/ProfileFragment.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_teammate_evalution.xml
  app/src/main/res/values/dimen.xml
Labels: 효림🌞, PR, feat

#68 [add/#67] 서버 통신을 위한 기본 파일 생성
  app/src/main/java/com/ssu/bilda/data/common/Page.kt
  app/src/main/java/com/ssu/bilda/data/common/PendingUser.kt
  app/src/main/java/com/ssu/bilda/data/common/Subject.kt
  app/src/main/java/com/ssu/bilda/data/common/SubjectWithTeamStatus.kt
  app/src/main/java/com/ssu/bilda/data/common/Team.kt
  app/src/main/java/com/ssu/bilda/data/common/TeamsOfSubject.kt
  app/src/main/java/com/ssu/bilda/data/common/User.kt
  app/src/main/java/com/ssu/bilda/data/enums/CompleteStatus.kt
  app/src/main/java/com/ssu/bilda/data/enums/RecruitmentStatus.kt
  app/src/main/java/com/ssu/bilda/data/enums/Role.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/ChangeNicknameRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/ChangePasswordRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/CreateTeamRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/SignInRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/SignUpRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/VerifyAuthCodeRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/request/VerifyEmailRequest.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/ChangeNicknameResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/ChangePasswordResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/TeamResponse.kt
  app/src/main/java/com/ssu/bilda/data/remote/response/UserResponse.kt
  app/src/main/java/com/ssu/bilda/data/service/EmailService.kt
  app/src/main/java/com/ssu/bilda/data/service/SubjectService.kt
  app/src/main/java/com/ssu/bilda/data/service/TeamService.kt
  app/src/main/java/com/ssu/bilda/data/service/UserService.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/EmailInputActivity.kt
Labels: 예린🌝, PR, add

#69 [feat/#43] 평가 페이지 seek bar 구현
  app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
  app/src/main/res/layout/fragment_teammate_evalution.xml
Labels: 효림🌞, PR, feat

#73 [feat/#72] 회원가입 api 붙이기 및 로그인 api + 세부 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssu/bilda/data/remote/App.kt
  app/src/main/java/com/ssu/bilda/data/remote/TokenSharedPreferences.kt
  app/src/main/java/com/ssu/bilda/data/service/EmailService.kt
  app/src/main/java/com/ssu/bilda/presentation/BnvActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/EmailInputActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/PwInputActivity.kt
  app/src/main/java/com/ssu/bilda/presentation/sign/SignInActivity.kt
  app/src/main/res/layout/activity_bnv.xml
  app/src/main/res/layout/activity_pw_input.xml
Labels: 예린🌝, PR, feat
